# Plugins
gems:
- jekyll-sitemap
safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME']


# Site Settings
title: "Women Techmakers GDG Cloud London"
description: "At Women Techmakers GDG Cloud London we are encouraging diversity in tech in GDG Cloud London since 2016. Get visibility, networking and resources to make the tech community of GDG Cloud London diverse and inclusive!"
baseurl: ""
url: "https://wtmGDG Cloud London.github.io"
permalink: "/blog/:title"
siteVerification: ""

# Organizer Info
organizerName: "WTM GDG Cloud London"
organizerAlternateName: "Women Techmakers GDG Cloud London"
organizerDescription: "At Women Techmakers GDG Cloud London we are encouraging diversity in tech in GDG Cloud London since 2015. Get visibility, networking and resources to make the tech community of GDG Cloud London diverse and inclusive!"
organizerLogo: "/img/wtm-logo.png"

# Head
metaKeywords: "wtm, diversityintech, womenintech, womentechmakers, google, programming, android, golang, javascript, chrome, developers, GDG Cloud London"
twitterAccount: "@gdgcloud"
socialImageSrcTwitter: "/img/wtm-logo.png"
socialImageSrcFacebook: "/img/wtm-logo.png"

# Documents

# Navigation
# Hero Block
heroImage: "hero.jpg"
heroTitle: "Women <typeout> GDG Cloud London"
eventDate: ""
typeoutTextValues: '"Techmakers", "Developers", "Designers", "Testers", "Managers"'
typeoutFallback: "Techmakers"
heroButtons:
 - {link: "https://www.meetup.com/women-techmakers-GDG Cloud London/?scroll=true", text: "Next Events"}

# About Block
aboutTitle: "About Women Techmakers GDG Cloud London"

# Latest News Block
latestNewsTitle: "Latest news"

# Footer
socialLinks:
 - {link: "https://twitter.com/gdgcloud", icon: "twitter"}
 - {permalink: "/feed.xml", icon: "rss"}
footerBlocks:
 -
  title: "Links"
  links:
   - {link: "https://twitter.com/gdgcloud", text: "Twitter"}
   - {link: "https://www.womentechmakers.com/", text: "Global Women Techmakers"}

 -
  title: "FAQ"

# Blog
blogTitle: "Latest news"
blogCommentsEnabled: false

# Speakers List Block
showSessions: false

# Team Block
teamBlockTitle: "About us"
aboutUs: "Your community as a woman in tech in GDG Cloud London. Get visibility, networking and resources for women in tech to drive innovation and participation in the field."

# Logistics Find Way Block
findWayTitle: "Find your way here"
findWayDistance: "Distance"
findWayDriving: "DRIVING"
findWayWalking: "WALKING"
findWayBicycling: "BICYCLING"
findWayTransit: "TRANSIT"
findWayFindFlight: "Find Flight"
logisticsMapCenterCoordinates: "49.056728, 3.117289"
logisticsMapMobileCenterCoordinates: "48.335365, 23.711648"
logisticsMapAutoDirections: false
